import type { InventoryState } from "./types";

export const seedData: InventoryState = {
  vehicles: [
    {
      id: "v1",
      stockNumber: "SY-2024-001",
      vin: "1HGCM82633A004352",
      make: "Honda",
      model: "Accord",
      year: 2018,
      color: "Silver",
      condition: "Good",
      yardLocation: "Row A-12",
      status: "in_yard",
      purchasePrice: 1200,
      listPrice: 2800,
      notes: "Runs, minor front damage",
      acquiredAt: "2024-09-15T00:00:00.000Z",
    },
    {
      id: "v2",
      stockNumber: "SY-2024-002",
      vin: "2T1BURHE0JC123456",
      make: "Toyota",
      model: "Corolla",
      year: 2016,
      color: "White",
      condition: "Fair",
      yardLocation: "Row B-05",
      status: "stripped",
      purchasePrice: 800,
      listPrice: 1500,
      notes: "Engine removed, body intact",
      acquiredAt: "2024-08-20T00:00:00.000Z",
    },
    {
      id: "v3",
      stockNumber: "SY-2024-003",
      vin: "3VWDP7AJ5DM123789",
      make: "Volkswagen",
      model: "Jetta",
      year: 2015,
      color: "Black",
      condition: "Poor",
      yardLocation: "Row C-08",
      status: "in_yard",
      purchasePrice: 500,
      listPrice: 900,
      notes: "Parts car only",
      acquiredAt: "2024-10-01T00:00:00.000Z",
    },
    {
      id: "v4",
      stockNumber: "SY-2024-004",
      vin: "1FTFW1ET5DFC12345",
      make: "Ford",
      model: "F-150",
      year: 2019,
      color: "Blue",
      condition: "Good",
      yardLocation: "Row A-03",
      status: "in_yard",
      purchasePrice: 3500,
      listPrice: 6500,
      notes: "4x4, clean title",
      acquiredAt: "2024-11-10T00:00:00.000Z",
    },
    {
      id: "v5",
      stockNumber: "SY-2023-089",
      vin: "5YJSA1E14HF123456",
      make: "Tesla",
      model: "Model S",
      year: 2017,
      color: "Red",
      condition: "Fair",
      yardLocation: "Sold",
      status: "sold",
      purchasePrice: 8000,
      listPrice: 12000,
      notes: "Sold as-is",
      acquiredAt: "2023-12-05T00:00:00.000Z",
    },
    {
      id: "v6",
      stockNumber: "SY-2024-005",
      vin: "WBA3B1C58EK123789",
      make: "BMW",
      model: "328i",
      year: 2014,
      color: "Gray",
      condition: "Good",
      yardLocation: "Row B-11",
      status: "in_yard",
      purchasePrice: 2200,
      listPrice: 4200,
      notes: "Luxury donor, many good parts",
      acquiredAt: "2024-11-25T00:00:00.000Z",
    },
  ],
  parts: [
    {
      id: "p1",
      sku: "ENG-HON-2018-001",
      name: "2.4L Engine Assembly",
      category: "Engine",
      condition: "Good",
      vehicleId: "v1",
      quantity: 1,
      unitPrice: 850,
      status: "available",
      notes: "78k miles, tested",
    },
    {
      id: "p2",
      sku: "TRN-HON-2018-001",
      name: "CVT Transmission",
      category: "Transmission",
      condition: "Good",
      vehicleId: "v1",
      quantity: 1,
      unitPrice: 450,
      status: "available",
      notes: "",
    },
    {
      id: "p3",
      sku: "BDY-HON-2018-001",
      name: "Front Bumper Assembly",
      category: "Body",
      condition: "Fair",
      vehicleId: "v1",
      quantity: 1,
      unitPrice: 120,
      status: "available",
      notes: "Minor scuff",
    },
    {
      id: "p4",
      sku: "ENG-TOY-2016-001",
      name: "1.8L Engine Block",
      category: "Engine",
      condition: "Good",
      vehicleId: "v2",
      quantity: 1,
      unitPrice: 650,
      status: "sold",
      notes: "Sold last month",
    },
    {
      id: "p5",
      sku: "INT-TOY-2016-001",
      name: "Dashboard Assembly",
      category: "Interior",
      condition: "Good",
      vehicleId: "v2",
      quantity: 1,
      unitPrice: 180,
      status: "available",
      notes: "",
    },
    {
      id: "p6",
      sku: "ELC-VW-2015-001",
      name: "Alternator",
      category: "Electrical",
      condition: "Good",
      vehicleId: "v3",
      quantity: 2,
      unitPrice: 75,
      status: "available",
      notes: "OEM refurbished",
    },
    {
      id: "p7",
      sku: "SUS-VW-2015-001",
      name: "Front Strut Pair",
      category: "Suspension",
      condition: "Fair",
      vehicleId: "v3",
      quantity: 1,
      unitPrice: 90,
      status: "available",
      notes: "",
    },
    {
      id: "p8",
      sku: "BDY-FRD-2019-001",
      name: "Tailgate Assembly",
      category: "Body",
      condition: "Excellent",
      vehicleId: "v4",
      quantity: 1,
      unitPrice: 350,
      status: "available",
      notes: "Chrome package",
    },
    {
      id: "p9",
      sku: "WHL-FRD-2019-001",
      name: "17\" Alloy Wheel Set (4)",
      category: "Wheels & Tires",
      condition: "Good",
      vehicleId: "v4",
      quantity: 1,
      unitPrice: 400,
      status: "reserved",
      notes: "Reserved for customer",
    },
    {
      id: "p10",
      sku: "ENG-BMW-2014-001",
      name: "N20 Turbo Engine",
      category: "Engine",
      condition: "Good",
      vehicleId: "v6",
      quantity: 1,
      unitPrice: 2200,
      status: "available",
      notes: "Low miles",
    },
    {
      id: "p11",
      sku: "INT-BMW-2014-001",
      name: "Leather Seat Set (Front)",
      category: "Interior",
      condition: "Excellent",
      vehicleId: "v6",
      quantity: 1,
      unitPrice: 450,
      status: "available",
      notes: "Heated seats",
    },
    {
      id: "p12",
      sku: "ELC-BMW-2014-001",
      name: "iDrive Head Unit",
      category: "Electrical",
      condition: "Good",
      vehicleId: "v6",
      quantity: 1,
      unitPrice: 280,
      status: "available",
      notes: "",
    },
    {
      id: "p13",
      sku: "GEN-BRK-001",
      name: "Universal Brake Caliper",
      category: "Brakes",
      condition: "Good",
      vehicleId: null,
      quantity: 5,
      unitPrice: 45,
      status: "available",
      notes: "Standalone stock",
    },
    {
      id: "p14",
      sku: "GEN-GLS-001",
      name: "Side Mirror (Universal Fit)",
      category: "Glass",
      condition: "Fair",
      vehicleId: null,
      quantity: 8,
      unitPrice: 35,
      status: "available",
      notes: "Mixed brands",
    },
    {
      id: "p15",
      sku: "GEN-ELC-001",
      name: "12V Car Battery",
      category: "Electrical",
      condition: "Good",
      vehicleId: null,
      quantity: 12,
      unitPrice: 65,
      status: "available",
      notes: "Tested, 90-day warranty",
    },
  ],
  sales: [
    {
      id: "s1",
      type: "vehicle",
      itemId: "v5",
      itemLabel: "2017 Tesla Model S (SY-2023-089)",
      amount: 11500,
      buyerName: "Mike Johnson",
      buyerPhone: "555-0101",
      paymentMethod: "transfer",
      soldAt: "2024-10-15T14:30:00.000Z",
    },
    {
      id: "s2",
      type: "part",
      itemId: "p4",
      itemLabel: "1.8L Engine Block (ENG-TOY-2016-001)",
      amount: 600,
      buyerName: "Auto Fix LLC",
      buyerPhone: "555-0102",
      paymentMethod: "check",
      soldAt: "2024-11-02T10:00:00.000Z",
    },
    {
      id: "s3",
      type: "part",
      itemId: "p6",
      itemLabel: "Alternator (ELC-VW-2015-001)",
      amount: 75,
      buyerName: "Sarah Williams",
      buyerPhone: "555-0103",
      paymentMethod: "cash",
      soldAt: "2024-11-20T16:45:00.000Z",
    },
    {
      id: "s4",
      type: "part",
      itemId: "p15",
      itemLabel: "12V Car Battery (GEN-ELC-001)",
      amount: 130,
      buyerName: "Dave's Garage",
      buyerPhone: "555-0104",
      paymentMethod: "card",
      soldAt: "2024-12-01T11:20:00.000Z",
    },
  ],
};
